#docker build -t chumpitazkasandra/backsheds .
#docker-compose build
#docker login -u chumpitazkasandra
#docker push chumpitazkasandra/backsheds:latest
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chumpitazkasandra/backsheds:latest
    ports:
      - "8081:8080"
    environment:
      - R2DBC_URL=${R2DBC_URL}
      - R2DBC_USERNAME=${R2DBC_USERNAME}
      - R2DBC_PASSWORD=${R2DBC_PASSWORD}
