server:
  port: 8080

spring:
  application:
    name: shed
  r2dbc:
    url: r2dbc:postgresql://ep-icy-sunset-a578ej1o.us-east-2.aws.neon.tech/shed?sslmode=require
    username: shed_owner
    password: LtCjN8zZmUa1
    show-sql: true
    pool:
      max-size: 20
      validation-query: SELECT 1
      initial-size: 5
  codec:
    max-in-memory-size: 10MB  # Aumenta el límite de bytes a 10 MB (ajusta según sea necesario)

logging:
  level:
    io.r2dbc: DEBUG