spring:
  application:
    name: shed
  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 9000
