apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-kasandra-chumpitaz-deployment
  namespace: kasandra-chumpitaz-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-kasandra-chumpitaz-deployment
  template:
    metadata:
      labels:
        app: backend-kasandra-chumpitaz-deployment
    spec:
      containers:
      - name: backend-container
        image: chumpitazkasandra/backsheds
        env:
          - name: db-host
            valueFrom:
              configMapKeyRef:
                name: kasandra-chumpitaz-configmap
                key: db-host
          - name: db-username
            valueFrom:
              configMapKeyRef:
                name: kasandra-chumpitaz-configmap
                key: db-username
          - name: db-password
            valueFrom:
              secretKeyRef:
                name: kasandra-chumpitaz-secret
                key: db-password